"""Add timestamps to Product

Revision ID: 0935d1729323
Revises: c2504cfd7cfa
Create Date: 2025-05-28 19:52:48.599101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0935d1729323'
down_revision = 'c2504cfd7cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bee_coin', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.drop_column('bee_coin_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bee_coin_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('bee_coin')

    # ### end Alembic commands ###
