"""initial

Revision ID: 217f7f71aa66
Revises: dccd80ab1e58
Create Date: 2025-05-28 01:12:01.903290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217f7f71aa66'
down_revision = 'dccd80ab1e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bee_coins',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bee_coins',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
