"""Add timestamps to Product

Revision ID: 46696ca899e9
Revises: fcaba86b994d
Create Date: 2025-05-28 18:20:34.962130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46696ca899e9'
down_revision = 'fcaba86b994d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
