"""initial

Revision ID: 6efb665b06dc
Revises: 
Create Date: 2025-05-27 19:36:31.595056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6efb665b06dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=192), nullable=True))
        batch_op.drop_column('registered_at')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('registered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
