"""initial

Revision ID: dccd80ab1e58
Revises: 6efb665b06dc
Create Date: 2025-05-28 01:10:16.972705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccd80ab1e58'
down_revision = '6efb665b06dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bee_coins', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('bee_coin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bee_coin', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('bee_coins')

    # ### end Alembic commands ###
